export const GET_CONFIGURATION_VARIABLES_REQUEST = 'GET_CONFIGURATION_VARIABLES_REQUEST';
export const GET_CONFIGURATION_VARIABLES_SUCCESS = 'GET_CONFIGURATION_VARIABLES_SUCCESS';
export const GET_CONFIGURATION_VARIABLES_FAILED = 'GET_CONFIGURATION_VARIABLES_FAILED';
